# post http://127.0.0.1:8000/api/login
# Content-Type: application/json
# Accept: application/json

# {
#     "email": "mouaz@gmail.com",
#     "password": "password"
# }

post http://127.0.0.1:8000/api/teacher/courses/3/add-marks
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|c7AzGG0pVuHPia0xdTo8oGyKqE6OYtLEXONSkyna

{
    "10": "-1",
    "11": "15",
    "12": "19",
    "13": "101"
}